### ISSUE TITLE
Always got: org.apache.axis.AxisFault: (404)Not Found

### ISSUE THREAD

**Issue by irvifa** [crealytics/spark-google-adwords#1]
Hello, I'm trying to use this library to query data from google ads words, but I always got this:

```
val df = sqlContext.read.format("com.crealytics.google.adwords").option("clientId",clientId).option("clientSecret",clientSecret).option("developerToken",a).option("refreshToken", f).option("reportType", "CAMPAIGN_PERFORMANCE_REPORT").option("clientCustomerId", "7945068155").option("userAgent", "Spark").option("during", "LAST_30_DAYS").load()
```
```
17/04/11 16:41:46 WARN soapXmlLogger: SOAP Request:
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Header>
        <ns1:RequestHeader xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201509" soapenv:mustUnderstand="0">
            <ns1:clientCustomerId>XXXX</ns1:clientCustomerId>
            <ns1:developerToken>4/XXXX</ns1:developerToken>
            <ns1:userAgent>Spark (AwApi-Java, AdWords-Axis/2.8.0, Common-Java/2.8.0, Axis/1.4, Java/1.8.0_121, maven)</ns1:userAgent>
            <ns1:validateOnly>false</ns1:validateOnly>
            <ns1:partialFailure>false</ns1:partialFailure>
        </ns1:RequestHeader>
    </soapenv:Header>
    <soapenv:Body>
        <getReportFields xmlns="https://adwords.google.com/api/adwords/cm/v201509">
            <reportType>CAMPAIGN_PERFORMANCE_REPORT</reportType>
        </getReportFields>
    </soapenv:Body>
</soapenv:Envelope>
```
```
17/04/11 16:41:46 WARN soapXmlLogger: SOAP Response:
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode xmlns:ns1="http://xml.apache.org/axis/">ns1:HTTP</faultcode>
            <faultstring>(404)Not Found</faultstring>
            <detail>
                <string>return code:  404
&lt;html&gt;&lt;body&gt;No service was found.&lt;/body&gt;&lt;/html&gt;</string>
                <ns2:HttpErrorCode xmlns:ns2="http://xml.apache.org/axis/">404</ns2:HttpErrorCode>
            </detail>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>
```
```
org.apache.axis.AxisFault: (404)Not Found
  at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:744)
  at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144)
  at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
  at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
  at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
  at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
  at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
  at org.apache.axis.client.Call.invoke(Call.java:2767)
  at org.apache.axis.client.Call.invoke(Call.java:2443)
  at org.apache.axis.client.Call.invoke(Call.java:2366)
  at org.apache.axis.client.Call.invoke(Call.java:1812)
  at com.google.api.ads.adwords.axis.v201509.cm.ReportDefinitionServiceSoapBindingStub.getReportFields(ReportDefinitionServiceSoapBindingStub.java:549)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.google.api.ads.common.lib.soap.SoapClientHandler.invoke(SoapClientHandler.java:109)
  at com.google.api.ads.common.lib.soap.axis.AxisHandler.invokeSoapCall(AxisHandler.java:230)
  at com.google.api.ads.common.lib.soap.SoapServiceClient.callSoapClient(SoapServiceClient.java:62)
  at com.google.api.ads.common.lib.soap.SoapServiceClient.invoke(SoapServiceClient.java:92)
  at com.sun.proxy.$Proxy28.getReportFields(Unknown Source)
  at com.crealytics.google.adwords.AdWordsClient.getFieldsForReportType(AdWordsClient.scala:35)
  at com.crealytics.google.adwords.AdWordsRelation.<init>(AdWordsRelation.scala:24)
  at com.crealytics.google.adwords.DefaultSource.createRelation(DefaultSource.scala:43)
  at com.crealytics.google.adwords.DefaultSource.createRelation(DefaultSource.scala:8)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
  ... 52 elided
```

Pretty much confused about this problem, could you help me about this issue?

Thanks.

**Comment by nightscape** [comment]
Hi @rvu95,

that's probably due to the fact that I had not updated the AdWords library in a while and the `v201509` from the log messages was sunset a while ago.
I just released version `0.9.0` and it should appear on the official Maven repos in a few hours.
Can you try that version and close this issue if it works with that?

**Comment by rvu95** [comment]
@nightscape waiting for the latest version :+1:

**Comment by nightscape** [comment]
Hmm, looks like a problem with the dependencies. I'm on vacation next week, so I won't have time to look into this... Can you try to dig a little deeper?

**Comment by nightscape** [comment]
Is this still relevant? If so, can you try with 0.9.2?

**Comment by irvifa** [comment]
NO, I'll close this issue, thank you.
