### ISSUE TITLE
NoSuchMethodError when loading DF

### ISSUE THREAD

**Issue by gersmann** [crealytics/spark-google-adwords#6]
I'm a first time Spark user and don't have many ideas what could be going on here. Do you know this problem?

Tested Spark 2.2.1 & 2.1.2

```
scala> val df = sqlContext.read.format("com.crealytics.google.adwords").option("clientId","xxxx.apps.googleusercontent.com").option("clientSecret","xxx").option("developerToken","xxx").option("refreshToken", "xxx").option("reportType", "CAMPAIGN_PERFORMANCE_REPORT").option("clientCustomerId", "246-097-xxxx").option("userAgent", "Spark").option("during", "LAST_30_DAYS").load()
18/01/07 21:42:09 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
  at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<init>(OfflineCredentials.java:89)
  at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<clinit>(OfflineCredentials.java:81)
  at com.crealytics.google.adwords.DefaultSource.createRelation(DefaultSource.scala:34)
  at com.crealytics.google.adwords.DefaultSource.createRelation(DefaultSource.scala:7)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
  ... 48 elided
```

```
	:: evicted modules:
	com.google.guava#guava;16.0.1 by [com.google.guava#guava;20.0] in [default]
	commons-logging#commons-logging;1.1.1 by [commons-logging#commons-logging;1.2] in [default]
	commons-logging#commons-logging;1.0.4 by [commons-logging#commons-logging;1.1.1] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   37  |   0   |   0   |   3   ||   34  |   0   |
	---------------------------------------------------------------------
```

**Comment by fabiorhs** [comment]
Same issue here, Spark 2.3.0.
Quite sure it's Guava-related but, even following hint provided [here](https://stackoverflow.com/questions/45334355/google-ads-api-java-client-library-java-lang-nosuchmethoderror-com-google-comm), we had no luck.
Did someone manage to solve this?
Thanks

`Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<init>(OfflineCredentials.java:89)
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<clinit>(OfflineCredentials.java:81)`

**Comment by nightscape** [comment]
Can you try again with 0.9.2?

**Comment by fabiorhs** [comment]
thank you for the release, but unfortunately it's not working yet.

```
spark 2.3.1
spark-google-adwords 0.9.2
```

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * com.google.guava:guava:20.0 is selected over 16.0.1
[warn]      +- com.google.api-ads:ads-lib:3.16.0                  (depends on 16.0.1)
[warn]      +- com.google.inject:guice:4.0                        (depends on 16.0.1)
```

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<init>(OfflineCredentials.java:89)
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<clinit>(OfflineCredentials.java:81)

```

**Comment by nightscape** [comment]
Hey @fabiorhs,

could you fork and try updating to the following dependencies and see if that helps?
https://mvnrepository.com/artifact/com.google.api-ads/ads-lib/4.1.0
https://mvnrepository.com/artifact/com.google.inject/guice/4.2.1
Both depend on guava >= 20, so maybe that solves the problem.
If that solves the problem I'd be happy to merge a corresponding PR 😄

**Comment by surya-zemoso** [comment]
Hi @nightscape I am trying to get the google ads report data and getting error something like - 
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.ads.common.lib.auth.OfflineCredentials$Api
  at com.crealytics.google.adwords.DefaultSource.createRelation(DefaultSource.scala:34)
  at com.crealytics.google.adwords.DefaultSource.createRelation(DefaultSource.scala:7)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
  ... 49 elided
Any suggestions ?
